# Generated by Django 4.2.4 on 2023-08-09 16:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KCACustomerDangerousData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_date', models.DateField(verbose_name='접수일')),
                ('age', models.IntegerField(verbose_name='연령')),
                ('injury_caused', models.CharField(max_length=50, verbose_name='위해 원인')),
                ('injury_item', models.CharField(max_length=50, verbose_name='위해 품목')),
                ('affected_area', models.CharField(max_length=50, verbose_name='위해 부위(환부)')),
                ('affected_place', models.CharField(max_length=50, verbose_name='위해 받은 장소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시각')),
                ('removed_at', models.DateTimeField(null=True, verbose_name='삭제시각')),
            ],
            options={
                'verbose_name': '한국소비자원 소비자 위해 데이터',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': '사용자',
            },
        ),
        migrations.CreateModel(
            name='Inference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='입력 연령')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시각')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.user', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '추론기능 이용자',
            },
        ),
    ]
